import { db, lotsTable } from "@workspace/db";
import { logger } from "./logger";
import { count } from "drizzle-orm";

const LOTS_DATA = [
  {
    name: "Bank of America",
    category: "bank",
    country: "США",
    description: "Открытие бизнес-счёта в одном из крупнейших банков США. Полное сопровождение, удалённо.",
    price: "1500",
    currency: "USD",
    timeline: "2-3 дня",
    features: ["Корпоративный счёт в USD", "SWIFT международные переводы", "Дебетовая карта Visa", "ACH-переводы внутри США", "Онлайн-банкинг"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Chase Business",
    category: "bank",
    country: "США",
    description: "Бизнес-счёт в JPMorgan Chase — один из самых надёжных банков мира.",
    price: "1800",
    currency: "USD",
    timeline: "1-3 дня",
    features: ["Корпоративная карта Visa", "ACH и Wire переводы", "Международные SWIFT-переводы", "Онлайн-банкинг", "Круглосуточная поддержка"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Mercury Bank",
    category: "bank",
    country: "США",
    description: "Современный онлайн-банк для стартапов и IT-компаний. Без скрытых комиссий.",
    price: "900",
    currency: "USD",
    timeline: "1-2 дня",
    features: ["Бесплатное обслуживание счёта", "API-интеграция для автоматизации", "Мультипользовательский доступ", "Виртуальные карты", "Счёт для нерезидентов США"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Relay Financial",
    category: "bank",
    country: "США",
    description: "Онлайн-бизнес-банк США с мощными инструментами управления финансами.",
    price: "800",
    currency: "USD",
    timeline: "1-2 дня",
    features: ["Без минимального остатка", "До 20 отдельных счётов", "Автоматизация платежей", "Интеграция с QuickBooks/Xero", "ACH и Wire переводы"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Revolut Business",
    category: "bank",
    country: "Великобритания/ЕС",
    description: "Ведущий европейский необанк для бизнеса. Поддержка 25+ валют.",
    price: "700",
    currency: "USD",
    timeline: "1-2 дня",
    features: ["25+ валют в одном счёте", "Мгновенные переводы", "Корпоративные карты", "Аналитика расходов", "Open Banking API"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Wise Business",
    category: "bank",
    country: "ЕС/Великобритания",
    description: "Многовалютный бизнес-счёт с минимальными комиссиями при конвертации.",
    price: "600",
    currency: "USD",
    timeline: "1-2 дня",
    features: ["50+ валют", "Реальный межбанковский курс обмена", "Дебетовые карты", "Международные SWIFT/SEPA переводы", "Пакетные массовые платежи"],
    logoUrl: null,
    available: true,
  },
  {
    name: "N26 Business",
    category: "bank",
    country: "Германия/ЕС",
    description: "Немецкий цифровой банк с полной европейской лицензией и IBAN.",
    price: "750",
    currency: "USD",
    timeline: "2-3 дня",
    features: ["Немецкий IBAN", "Mastercard бизнес-карта", "SEPA-переводы по ЕС", "Без скрытых комиссий", "Полностью дистанционное обслуживание"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Bunq Business",
    category: "bank",
    country: "Нидерланды/ЕС",
    description: "Голландский банк с нидерландской лицензией. Идеально для ЕС-операций.",
    price: "850",
    currency: "USD",
    timeline: "2-3 дня",
    features: ["Нидерландский IBAN", "До 25 суб-счётов", "SEPA/SWIFT переводы", "API доступ", "Мультипользовательское управление"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Stripe Персональный",
    category: "payment_system",
    country: "США/Весь мир",
    description: "Персональный аккаунт Stripe для приёма онлайн-платежей по всему миру. Полное сопровождение под ключ.",
    price: "1450",
    currency: "USD",
    timeline: "От 2-5 дней",
    features: ["Приём карт Visa/MC/Amex", "Персональный аккаунт", "Webhooks и полный API", "Поддержка 135+ валют", "Мгновенные выплаты на карту"],
    logoUrl: null,
    available: true,
  },
  {
    name: "PayPal Бизнес",
    category: "payment_system",
    country: "США/Весь мир",
    description: "Верифицированный бизнес-аккаунт PayPal. Приём платежей из 200+ стран. Полное сопровождение под ключ.",
    price: "1550",
    currency: "USD",
    timeline: "5-10 дней",
    features: ["Приём платежей из 200+ стран", "PayPal Checkout для сайта", "Защита продавца", "Массовые выплаты партнёрам", "Конвертация валют"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Payoneer Персональный",
    category: "payment_system",
    country: "США/Весь мир",
    description: "Персональный аккаунт Payoneer по программе приоритетного обслуживания. Полное сопровождение под ключ.",
    price: "2000",
    currency: "USD",
    timeline: "До 5 дней",
    features: ["Приоритетное обслуживание", "Персональный аккаунт", "Mastercard карта", "Вывод в 200+ стран", "Мультивалютный баланс"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Square Business",
    category: "payment_system",
    country: "США",
    description: "Платёжный аккаунт Square — идеален для e-commerce и физических точек продаж.",
    price: "900",
    currency: "USD",
    timeline: "2-3 дня",
    features: ["POS-система для оффлайн продаж", "Онлайн-магазин", "Выставление счетов", "Управление запасами", "Аналитика продаж"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Offshore Bank (BVI)",
    category: "offshore",
    country: "Британские Виргинские острова",
    description: "Регистрация офшорного банка на BVI с международной лицензией. Под ключ.",
    price: "15000",
    currency: "USD",
    timeline: "14-21 день",
    features: ["Банковская лицензия BVI", "Конфиденциальность бенефициаров", "0% корпоративный налог на Британских Виргинских Островах", "Корреспондентский счёт в Европе", "Принятие международных SWIFT-переводов"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Offshore Bank (Каймановы о-ва)",
    category: "offshore",
    country: "Каймановы острова",
    description: "Открытие офшорного банка на Каймановых островах. Высшая степень конфиденциальности.",
    price: "18000",
    currency: "USD",
    timeline: "21-30 дней",
    features: ["Полная банковская лицензия", "Конфиденциальность акционеров", "Международные SWIFT-переводы", "Отсутствие валютного контроля", "Правовое сопровождение"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Инвестиционный Фонд (ЕС)",
    category: "offshore",
    country: "Люксембург/Ирландия",
    description: "Регистрация инвестиционного фонда в ЕС с соответствующей лицензией UCITS/AIF.",
    price: "12000",
    currency: "USD",
    timeline: "30-45 дней",
    features: ["Лицензия EU (AIFMD/UCITS)", "Структура UCITS или AIF", "Доступ к европейским инвесторам", "Управляющая компания в ЕС", "Квалифицированный кастодиан"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Криптобиржа (Эстония)",
    category: "crypto",
    country: "Эстония/ЕС",
    description: "Регистрация криптовалютной биржи с лицензией VASP в Эстонии. Быстро и легально.",
    price: "8000",
    currency: "USD",
    timeline: "14-30 дней",
    features: ["VASP лицензия ЕС", "Обязательная AML/KYC система", "Юридическое сопровождение", "Открытие банковского счёта для биржи", "Действие лицензии на всей территории ЕС"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Криптобиржа (BVI/Сейшелы)",
    category: "crypto",
    country: "BVI / Сейшелы",
    description: "Офшорная криптобиржа с лицензией. Минимальные требования к капиталу.",
    price: "6000",
    currency: "USD",
    timeline: "10-21 день",
    features: ["Офшорная лицензия VASP", "Конфиденциальность владельцев", "Минимальный уставной капитал", "Ускоренная регистрация", "Юридическое оформление под ключ"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Payoneer Бизнес",
    category: "payment_system",
    country: "США/Весь мир",
    description: "Бизнес-аккаунт Payoneer по программе приоритетного обслуживания. Для компаний и предпринимателей.",
    price: "2000",
    currency: "USD",
    timeline: "До 5 дней",
    features: ["Приоритетное обслуживание", "Бизнес-аккаунт", "Массовые выплаты партнёрам", "API-интеграция", "Мультивалютный баланс"],
    logoUrl: null,
    available: true,
  },
  {
    name: "Stripe Бизнес",
    category: "payment_system",
    country: "США/Весь мир",
    description: "Бизнес-аккаунт Stripe с полной верификацией. Для компаний и платформ, работающих по всему миру.",
    price: "1450",
    currency: "USD",
    timeline: "От 2-5 дней",
    features: ["Stripe Connect для маркетплейсов", "Подписки и рекуррентные платежи", "Stripe Radar (антифрод)", "Полный доступ к API", "Выплаты в 40+ стран"],
    logoUrl: null,
    available: true,
  },
];

export async function seedLotsIfEmpty() {
  try {
    const [{ value: lotsCount }] = await db.select({ value: count() }).from(lotsTable);
    if (lotsCount > 0) {
      logger.info({ lotsCount }, "Lots already seeded, skipping");
      return;
    }

    logger.info("Lots table is empty, seeding...");
    await db.insert(lotsTable).values(LOTS_DATA);
    logger.info({ count: LOTS_DATA.length }, "Lots seeded successfully");
  } catch (err) {
    logger.error({ err }, "Failed to seed lots");
  }
}
